
swagger: "2.0"
info:
    title: Argent Bank Transaction API
    description: API model proposal for user transactions
    version: 2.0.0
    termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
    - http
paths:
    /user/transactions:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Get current month's transactions
            description: Route for fetching all the current month 's transactions
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: User transactions retrieved successfully
                    schema:
                        $ref: "#/definitions/currentMonthTransactions"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transactions not found
                "500":
                    description: Internal Server Error
    /user/transaction/{ID}:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Get specific transaction
            description: Route for fetching a specific transaction with it's ID
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: ID
                  description: ID of the targeted transaction
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction retrieved successfully
                    schema:
                        $ref: "#/definitions/specificTransaction"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Edit transaction informations
            description: Route for adding or updating transaction's information
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: ID
                  description: ID of the transaction to edit
                  required: true
                  type: string
                - in: body
                  name: body
                  description: New transaction informations
                  required: true
                  schema:
                      $ref: "#/definitions/editTransaction"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction edited successfully
                    schema:
                        $ref: "#/definitions/editTransactionResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
        delete:
            security:
                - Bearer: []
            tags:
                - Transaction module
            summary: Delete informations of specific transaction
            description: Route for deleting allowed elements of a transaction (category, note)
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: ID
                  description: ID of the transaction whose informations is to be deleted
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Informations to delete
                  required: true
                  schema:
                      $ref: "#/definitions/deleteInformationTransaction"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction edited successfully
                    schema:
                        $ref: "#/definitions/deleteInformationTransactionResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    currentMonthTransactions:
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    transaction_0:
                        type: object
                        description: First transaction
                        properties:
                            id:
                                type: string
                                description: Id of the first transaction
                            transactionType:
                                type: string
                                description: Type of the first transaction
                            date:
                                type: string
                                description: Date of the first transaction
                            amount:
                                type: number
                                description: Amount of the first transaction
                            description:
                                type: string
                                description: Description of the first transaction
                            category:
                                type: string
                                description: Category of the first transaction
                            notes:
                                type: string
                                description: Notes of the first transaction
                    transaction_1:
                        type: object
                        description: Second transaction
                        properties:
                            id:
                                type: string
                                description: Id of the second transaction
                            transactionType:
                                type: string
                                description: Type of the second transaction
                            date:
                                type: string
                                description: Date of the second transaction
                            amount:
                                type: number
                                description: Amount of the second transaction
                            description:
                                type: string
                                description: Description of the second transaction
                            category:
                                type: string
                                description: Category of the second transaction
                            notes:
                                type: string
                                description: Notes of the second transaction
    specificTransaction:
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    id:
                        type: string
                        description: Id of the transaction
                    transactionType:
                                type: string
                                description: Type of the second transaction
                    date:
                        type: string
                        description: Date of the transaction
                    amount:
                        type: number
                        description: Amount of the transaction
                    description:
                        type: string
                        description: Description of the transaction
                    category:
                        type: string
                        description: Category of the transaction
                    notes:
                        type: string
                        description: Notes of the transaction
    editTransaction:
        properties:
            category:
                type: string
                description: Add/Update category of this transaction
            notes:
                type: string
                description: Add/Update notes of this transaction
    editTransactionResponse:
         properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    id:
                        type: string
                        description: Id of the transaction
                    transactionType:
                                type: string
                                description: Type of the second transaction
                    date:
                        type: string
                        description: Date of the transaction
                    amount:
                        type: number
                        description: Amount of the transaction
                    description:
                        type: string
                        description: Description of the transaction
                    category:
                        type: string
                        description: Category of the transaction
                    notes:
                        type: string
                        description: Notes of the transaction
    deleteInformationTransaction:
         properties:
            category:
                type: boolean
                description: delete category's informations of this transaction
            notes:
                type: boolean
                description: Delete notes informations of this transaction
    deleteInformationTransactionResponse:
         properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    id:
                        type: string
                        description: Id of the transaction
                    transactionType:
                                type: string
                                description: Type of the second transaction
                    date:
                        type: string
                        description: Date of the transaction
                    amount:
                        type: number
                        description: Amount of the transaction
                    description:
                        type: string
                        description: Description of the transaction
                    category:
                        type: string
                        description: Category of the transaction
                    notes:
                        type: string
                        description: Notes of the transaction